import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { SessionProvider } from 'next-auth/react';
import Footer from '@/components/shared/Footer';
import Navbar from '@/components/shared/Navbar';
import { ThemeProvider } from '@/lib/ThemeProvider';
import { Toaster } from 'sonner';
import ProductForm from '@/components/product/ProductForm';
import { Separator } from '@/components/ui/separator';
import { Suspense } from 'react';
import Loading from './loading';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="flex flex-col justify-between min-h-screen bg-secondary">
              <Navbar />
              <ProductForm />
              <Separator className="my-5" />
              <div className="grid grid-cols-5 px-4 flex-grow">
                <div className="col-span-1">left menu</div>
                <div className="col-span-4 space-y-4">
                  <Suspense fallback={<Loading />}>
                    <main>{children}</main>
                  </Suspense>
                </div>
              </div>

              <Footer />
            </div>
            <Toaster richColors />
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
