import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { SessionProvider } from 'next-auth/react';
import Footer from '@/components/shared/Footer';
import Navbar from '@/components/shared/Navbar';
import { ThemeProvider } from '@/lib/ThemeProvider';
import { Toaster } from 'sonner';
import ProductForm from '@/components/product/ProductForm';
import { Separator } from '@/components/ui/separator';
import { Suspense } from 'react';
import Loading from './loading';
import Filters from '@/components/filter/Filters';
import CloseFilters from '@/components/filter/CloseFilters';
import db from '@/lib/db';
import { CartContextProvider } from '@/context/CartContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cartItems = await db.cart.findMany({ include: { product: true } });
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <CartContextProvider cart={cartItems}>
              <div className="flex flex-col justify-between min-h-screen bg-secondary">
                <Navbar />
                {/* <ProductForm /> */}
                <CloseFilters />
                <Separator className="my-5" />
                <div className="grid grid-cols-6 px-4 flex-grow gap-2">
                  <div className="col-span-1">
                    <Filters />
                  </div>
                  <div className="col-span-5 space-y-4">
                    <Suspense fallback={<Loading />}>
                      <main>{children}</main>
                    </Suspense>
                  </div>
                </div>

                <Footer />
              </div>
            </CartContextProvider>
            <Toaster richColors />
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
